### ISSUE TITLE
Why not use C#?

### ISSUE THREAD

**Issue by TapsJoy** [Gramosa/ECS-Brazuca#1]
One of the main reasons for using ECS is performance. In terms of performance, isn't C# a better choice?

**Comment by Gramosa** [comment]
Oh thanks for commenting, yes you are right that C# codes runs faster than GDScript, but I don't have done codes in C#, so my knowledge about the language are very basic. In fact, this project is more like a "training". Several parts of the code are inefficient, so I intend to improve little by little (unfortunately I don't have much free time).

**Comment by TapsJoy** [comment]
Thanks for your reply. I'm looking for an alternative to Unity DOTS. Don't mind what I said, for Godot, I'm just getting started with it.
